"""User-executed action types for pool management.

This module defines the types used to record actions that the user actually
performed on the pool.  It is the canonical home for:

- :class:`ActionType` -- what category of action was performed.
- :class:`ActionSource` -- what triggered the action.
- :class:`Action` -- a record of a single user-executed pool operation.

Distinction from :mod:`.recommendation`
-----------------------------------------
- A :class:`~.recommendation.Recommendation` describes *what to do*,
  generated by the analysis pipeline.
- An :class:`Action` records *what was done*, logged after the fact by the
  user or an automation.

When an action originates from a recommendation (``source ==
:attr:`ActionSource.RECOMMENDATION``), the :attr:`~Action.recommendation_id`
field links back to the originating recommendation.

This separation enables future features such as:

- Treatment history and audit log (#19, #92).
- Inventory tracking and product consumption (#94).
- Automatic feedback loop: mark a recommendation as resolved once the
  corresponding action is recorded.

No Home Assistant dependency is present in this module.

Example::

    from datetime import datetime, UTC
    from custom_components.poolman.domain.action import Action, ActionType, ActionSource

    action = Action(
        id="act_20260419_ph_minus",
        type=ActionType.CHEMICAL,
        source=ActionSource.USER,
        treatment_id="ph_minus_300g",
        product_id="ph_minus",
        quantity=300.0,
        unit="g",
        timestamp=datetime.now(UTC),
    )
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import StrEnum


class ActionType(StrEnum):
    """Category of a user-executed pool action.

    Attributes:
        CHEMICAL: Application of a chemical product (pH correction,
            chlorination, algae treatment, etc.).
        CLEANING: Physical cleaning operation (vacuuming, brushing,
            backwash, etc.).
        MAINTENANCE: Equipment maintenance (pump check, filter replacement,
            sensor calibration, etc.).
    """

    CHEMICAL = "chemical"
    CLEANING = "cleaning"
    MAINTENANCE = "maintenance"


class ActionSource(StrEnum):
    """What triggered a pool action.

    Attributes:
        USER: The user recorded the action manually (e.g., via the HA
            service call UI or a Lovelace button).
        RECOMMENDATION: The action was taken in response to a
            :class:`~.recommendation.Recommendation` generated by the
            analysis pipeline.  :attr:`~Action.recommendation_id` must be
            set when this source is used.
        AUTOMATION: The action was triggered by a Home Assistant
            automation or script without direct user input.
    """

    USER = "user"
    RECOMMENDATION = "recommendation"
    AUTOMATION = "automation"


@dataclass(frozen=True)
class Action:
    """A record of a single user-executed pool operation.

    Captures what was done, when, how much, and why (source + optional link
    to the originating recommendation).  All fields that identify optional
    context are ``None`` when not applicable.

    Attributes:
        id: Unique identifier for this action record, e.g.
            ``"act_20260419_ph_minus"``.
        type: Category of action performed (:class:`ActionType`).
        source: What triggered this action (:class:`ActionSource`).
        treatment_id: Identifier of the :class:`~.recommendation.Treatment`
            step that was followed, e.g. ``"ph_minus_300g"``.
        recommendation_id: Identifier of the originating
            :class:`~.recommendation.Recommendation` when
            ``source == ActionSource.RECOMMENDATION``, otherwise ``None``.
        product_id: Identifier of the chemical product from
            :class:`~.model.ChemicalProduct`, e.g. ``"ph_minus"``, or
            ``None`` for non-chemical actions.
        quantity: Amount applied (e.g., grams of product, minutes of
            cleaning).
        unit: Unit for :attr:`quantity`.  MUST be a Home Assistant-compatible
            unit string, e.g. ``"g"``, ``"mL"``, ``"tablet"``, or ``"min"``.
        timestamp: When the action was performed (timezone-aware).
        duration: How long the action took, e.g. ``timedelta(minutes=30)``
            for a cleaning session, or ``None`` when not applicable.
    """

    id: str
    type: ActionType
    source: ActionSource
    treatment_id: str
    quantity: float
    unit: str  # HA-compatible unit: "g", "mL", "tablet", "min", …
    timestamp: datetime
    recommendation_id: str | None = None
    product_id: str | None = None
    duration: timedelta | None = None
