"""Canonical problem types for pool water-quality diagnostics.

This module is the single source of truth for:

- :class:`Severity` -- how serious a problem is.
- :class:`MetricName` -- canonical names for the pool chemistry metrics.
- :class:`ChemistryStatus` -- good / warning / bad status for a single
  parameter.
- :class:`ParameterReport` -- a self-describing status report for one metric.
- :class:`Problem` -- a normalized representation of a single water-quality
  issue.

These types are imported by :mod:`.model`, :mod:`.recommendation`, and
:mod:`.analysis`; they must never depend on those modules (no circular
imports).

No Home Assistant dependency is present in this module.

Example::

    from custom_components.poolman.domain.problem import Problem, Severity

    problem = Problem(
        code="ph_too_high",
        message="pH is too high: 8.2 (expected 6.8-7.8)",
        severity=Severity.CRITICAL,
        metric=MetricName.PH,
        value=8.2,
        expected_range=(6.8, 7.8),
    )
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class Severity(StrEnum):
    """Severity levels for a detected water-quality problem.

    Ordered from least to most urgent:

    - :attr:`LOW` -- parameter is drifting toward a boundary but still within
      the acceptable range.  Monitor; no immediate action required.
    - :attr:`MEDIUM` -- parameter is slightly outside the acceptable range.
      Action is recommended soon.
    - :attr:`CRITICAL` -- parameter is far outside the acceptable range.
      Immediate action is required.

    All values serialize as plain strings (``"low"``, ``"medium"``,
    ``"critical"``) because :class:`Severity` inherits from
    :class:`~enum.StrEnum`.
    """

    LOW = "low"
    MEDIUM = "medium"
    CRITICAL = "critical"


class MetricName(StrEnum):
    """Canonical names for the pool chemistry metrics.

    Used to identify which parameter a :class:`Problem` or
    :class:`ParameterReport` refers to.
    """

    PH = "ph"
    ORP = "orp"
    CHLORINE = "chlorine"
    TEMPERATURE = "temperature"
    CYA = "cya"
    ALKALINITY = "alkalinity"
    HARDNESS = "hardness"
    TDS = "tds"
    SALT = "salt"
    EC = "ec"


class ChemistryStatus(StrEnum):
    """Status of a single chemistry parameter.

    - :attr:`GOOD` -- value is within the acceptable range and close to target.
    - :attr:`WARNING` -- value is within min/max but score is below 50 (drifting).
    - :attr:`BAD` -- value is outside min or max.
    """

    GOOD = "good"
    WARNING = "warning"
    BAD = "bad"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------


class ParameterReport(BaseModel, frozen=True):
    """Status report for a single chemistry parameter.

    Produced by :func:`~.chemistry.compute_parameter_status` and aggregated
    into :class:`~.model.ChemistryReport`.

    Attributes:
        metric: Which parameter this report covers.
        status: Overall status classification.
        value: The measured value that was evaluated.
        target: The ideal target value.
        minimum: Lower bound of the acceptable range.
        maximum: Upper bound of the acceptable range.
        score: Quality score from 0 (worst) to 100 (perfect).
    """

    metric: MetricName
    status: ChemistryStatus
    value: float
    target: float
    minimum: float
    maximum: float
    score: int = Field(ge=0, le=100)


# ---------------------------------------------------------------------------
# Problem
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Problem:
    """A normalized representation of a single water-quality issue.

    A :class:`Problem` is generated by a :class:`~.rules.base.Rule` for every
    chemistry parameter that deviates from its acceptable range.  It carries
    enough information for dashboards, logs, and downstream services to
    understand the nature and urgency of the issue without containing any
    treatment advice.

    All fields except :attr:`code`, :attr:`message`, and :attr:`severity` are
    optional to support partial or missing sensor data gracefully.

    Attributes:
        code: Machine-readable identifier, e.g. ``"ph_too_high"`` or
            ``"orp_too_low"``.  Follows the pattern
            ``"{metric}_{direction}"`` where direction is one of
            ``"too_high"``, ``"too_low"``, or ``"out_of_range"``.
        message: Human-readable description of the problem, including the
            measured value and expected range.
        severity: How serious the deviation is
            (:attr:`Severity.LOW`, :attr:`Severity.MEDIUM`, or
            :attr:`Severity.CRITICAL`).
        metric: The canonical :class:`MetricName` for the affected parameter,
            or ``None`` when the parameter has no known mapping.
        value: The actual measured value that triggered the problem, or
            ``None`` when the value is unavailable.
        expected_range: ``(minimum, maximum)`` tuple representing the
            acceptable range for this parameter, or ``None`` when the range
            is unknown.
    """

    code: str
    message: str
    severity: Severity
    metric: MetricName | None
    value: float | None
    expected_range: tuple[float, float] | None
