name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync
      - uses: j178/prek-action@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: uv sync
      - name: Run tests with coverage
        run: uv run poe cover --color=yes -o junit_family=legacy

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          directory: reports

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() }}
        with:
          directory: reports
          report_type: test_results

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: home-assistant/actions/hassfest@master

  # TODO: uncomment when the repository is public
  # hacs:
  #   name: HACS
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: hacs/action@main
  #       with:
  #         category: integration
